CREATE SCHEMA IF NOT EXISTS MY_DB;
use MY_DB;
DROP TABLE IF EXISTS `MY_DB_TABLE`;
CREATE TABLE `MY_DB_TABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOTE` varchar(100) DEFAULT NULL,
  `ROW_CREATED` datetime DEFAULT current_timestamp(),
  `ROW_UPDATED` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;

